# 服务器配置
server:
  port: 8081
  servlet:
    context-path: /uhouse
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uhouse?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


